#阿里source
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
platform :ios, '10.0'
inhibit_all_warnings!#去掉pod的工程中的警告
use_frameworks!

target 'JFCitySelector Demo' do

pod 'YYModel'

end
